spring.application.name=portfolio

# Supabase
supabase.url=https://qmloowixxghwzkanhcyl.supabase.co
supabase.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtbG9vd2l4eGdod3prYW5oY3lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxNjc2ODMsImV4cCI6MjA5MDc0MzY4M30.l7_dFZ9ftSfJodIc7grVz7s74ExUNjdH5z1F8s08Yl8
